### ISSUE TITLE
Add option to not show courses that do not have any results

### ISSUE THREAD

**Issue by scott56gps** [byuitechops/d2l-pages-search#28]
Ideas:
- Make a checkbox in the search section

**Comment by tallroids** [comment]
Should this be an option or default?

**Comment by scott56gps** [comment]
I believe Brother McKinney wants that to be default so that on large
searches, it doesn't waste the extra processing power to display just the
name.  Check with Josh and Corey on that too make sure though.


Scott Nicholes

**Comment by meeple142** [comment]
I would say default to not show courses that do not have any results. Thanks Scott!

**Comment by meeple142** [comment]
that was confusing. The default should be to hide courses that do not have any results.

**Comment by scott56gps** [comment]
No problem!  Glad I can still help :)
